### ISSUE TITLE
move GraphLaplacians.jl here?

### ISSUE THREAD

**Issue by CarloLucibello** [yuehhua/GraphSignals.jl#48]
It seems there is little use for
https://github.com/yuehhua/GraphLaplacians.jl
as a standalone package, the few utilities it contains could be distributed here and in LigthGraphs.jl to simplify maintainance.

**Comment by yuehhua** [comment]
Sure. However, I am not sure that LightGraphs.jl is willing to maintain some functionality about Laplacian and maybe their gradients.

**Comment by CarloLucibello** [comment]
I don't think the deal with diff rules, maybe better to move it entirely here than

**Comment by yuehhua** [comment]
Actually, they have NO diff rules. However, sometimes AD is going to differentiate the conversion of an adjacency matrix into a Laplacian matrix. I don't know why. So, I decide to add `@nograd` to them to force not differentiate the conversions.

**Comment by yuehhua** [comment]
Currently, I consider to move GraphLaplacians.jl to LigthGraphs.jl and SimpleWeightedGraphs.jl.
